eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://students
          predicates:
            - Path=/api/v1/students/**
          filters:
            - AuthenticationFilter

        - id: schools
          uri: lb://schools
          predicates:
            - Path=/api/v1/schools/**
          filters:
            - AuthenticationFilter

        - id: users
          uri: lb://users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
  logging:
    level:
      org:
        springframework:
          security: DEBUG
          cloud:
            gateway: DEBUG
management:
  tracing:
    sampling:
      probability: 1.0
