eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8758
spring:
  application:
    name: users
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: zest12345
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

management:
  tracing:
    sampling:
      probability: 1.0